### PR TITLE
Fix JSON request.

### PR DESCRIPTION
**Pull request by kazken3**
JSON request uses in this script does not work on these condition now.
Condition:Node.js 0.12.4 , CoffeeScript 1.9.3 and hubot 2.12.0

This patch works well.

### CODE REVIEW

**Comment by bouzuya** [comment]
Sorry, I don't know what you want to. Could you add the compiled JavaScript code.
I think that there is no diffs.

**Comment by kazken3** [comment]
> Could you add the compiled JavaScript code.
> I think that there is no diffs.

I tried compiled these scripts, but result is same JavaSctipt files you wrote.
But, works by hubot, result is different.

This is steps to reproduce. Please reconfirm it.
1. Setup Node.js by nvm.
2. npm install -g coffee-script 
3. npm install -g yo generator-hubot
4. mkdir hubot && cd hubot
5. yo hubot
6. npm install https://github.com/bouzuya/hubot-docomo-dialogue/archive/master.tar.gz
7. Edit external-scripts.json for add "hubot-docomo-dialogue".
8. export HUBOT_DOCOMO_DIALOGUE_API_KEY=MYAPIKEY
9. export HUBOT_DOCOMO_DIALOGUE_P=1
10. ./bin/hubot -a shell
11. Type some words and enter return key.

Works procedure 11th, displays errors below.

```
~/hubot$ ./bin/hubot -a shell 
hubot> [Thu Jul 16 2015 01:59:17 GMT+0900 (JST)] INFO hubot-redis-brain: Using default redis on localhost:6379
hubot> hello
[Thu Jul 16 2015 01:59:22 GMT+0900 (JST)] ERROR TypeError: undefined is not a function
  at TextListener.callback (/home/***/hubot/node_modules/hubot-docomo-dialogue/src/scripts/docomo-dialogue.coffee:34:7, <js>:20:59)
  at TextListener.Listener.call (/home/***/hubot/node_modules/hubot/src/listener.coffee:43:7, <js>:37:14)
  at Robot.receive (/home/***/hubot/node_modules/hubot/src/robot.coffee:230:9, <js>:154:33)
  at Shell.Adapter.receive (/home/***/hubot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at [object Object].listener (/home/***/hubot/node_modules/hubot/src/adapters/shell.coffee:48:7, <js>:92:22)
  at [object Object].Cli.parse (/home/***/hubot/node_modules/hubot/node_modules/cline/index.js:320:35)
  at [object Object].<anonymous> (/home/***/hubot/node_modules/hubot/node_modules/cline/index.js:182:18)
  at [object Object].defaultFn (/home/***/hubot/node_modules/hubot/node_modules/cline/index.js:53:13)
  at [object Object].fn (/home/***/hubot/node_modules/hubot/node_modules/cline/index.js:217:23)
  at Interface.<anonymous> (/home/***/hubot/node_modules/hubot/node_modules/cline/index.js:148:18)
  at Interface.emit (events.js:107:17)
  at Interface._onLine (readline.js:214:10)
  at Interface._line (readline.js:553:8)
  at Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:110:17)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:538:20)
```

**Comment by bouzuya** [comment]
I expect to load the js files only. Please wait a little, because I'll check it.

**Comment by bouzuya** [comment]
Sorry, I specified the wrong scripts path. I fixed it in `1.1.1`.

ref:  https://github.com/bouzuya/hubot-docomo-dialogue/commit/76b6837445a5cb7afd3fa8bf6b26b34d4cf9122a

**Pull request closed without merging**
